version: '3.1'

services:

  db:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    container_name: meu-db
    
  app:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    container_name: meu-app